/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-surface": "var(--color-inverse-surface)",
        "outline": "var(--color-outline)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-error": "var(--color-on-error)",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "error-container": "var(--color-error-container)",
        "primary": "var(--color-primary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "background": "var(--color-background)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "secondary-container": "var(--color-secondary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface": "var(--color-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-background": "var(--color-on-background)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-primary": "var(--color-on-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "secondary": "var(--color-secondary)",
        "primary-container": "var(--color-primary-container)",
        "error": "var(--color-error)",
        "surface-dim": "var(--color-surface-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "mesh-blue-tint": "var(--color-mesh-blue-tint)",
        "glass-border": "var(--color-glass-border)",
        "glass-bg": "var(--color-glass-bg)",
      },
      borderRadius: {
        "DEFAULT": "var(--border-radius-DEFAULT)",
        "lg": "var(--border-radius-lg)",
        "xl": "var(--border-radius-xl)",
        "full": "var(--border-radius-full)",
      },
      spacing: {
        "margin-desktop": "var(--spacing-margin-desktop)",
        "container-max": "var(--spacing-container-max)",
        "gutter": "var(--spacing-gutter)",
        "margin-mobile": "var(--spacing-margin-mobile)",
        "unit": "var(--spacing-unit)",
        "section-padding": "var(--spacing-section-padding)",
      },
      fontSize: {
        "headline-lg-mobile": ["var(--font-size-headline-lg-mobile)", {
          lineHeight: "var(--line-height-headline-lg-mobile)",
          letterSpacing: "var(--letter-spacing-headline-lg-mobile)",
          fontWeight: "var(--font-weight-headline-lg-mobile)",
        }],
        "label-md": ["var(--font-size-label-md)", {
          lineHeight: "var(--line-height-label-md)",
          letterSpacing: "var(--letter-spacing-label-md)",
          fontWeight: "var(--font-weight-label-md)",
        }],
        "body-lg": ["var(--font-size-body-lg)", {
          lineHeight: "var(--line-height-body-lg)",
          letterSpacing: "var(--letter-spacing-body-lg)",
          fontWeight: "var(--font-weight-body-lg)",
        }],
        "display-lg": ["var(--font-size-display-lg)", {
          lineHeight: "var(--line-height-display-lg)",
          letterSpacing: "var(--letter-spacing-display-lg)",
          fontWeight: "var(--font-weight-display-lg)",
        }],
        "headline-xl": ["var(--font-size-headline-xl)", {
          lineHeight: "var(--line-height-headline-xl)",
          letterSpacing: "var(--letter-spacing-headline-xl)",
          fontWeight: "var(--font-weight-headline-xl)",
        }],
        "headline-lg": ["var(--font-size-headline-lg)", {
          lineHeight: "var(--line-height-headline-lg)",
          letterSpacing: "var(--letter-spacing-headline-lg)",
          fontWeight: "var(--font-weight-headline-lg)",
        }],
        "body-md": ["var(--font-size-body-md)", {
          lineHeight: "var(--line-height-body-md)",
          letterSpacing: "var(--letter-spacing-body-md)",
          fontWeight: "var(--font-weight-body-md)",
        }],
        "display-lg-mobile": ["var(--font-size-display-lg-mobile)", {
          lineHeight: "var(--line-height-display-lg-mobile)",
          letterSpacing: "var(--letter-spacing-display-lg-mobile)",
          fontWeight: "var(--font-weight-display-lg-mobile)",
        }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
